version: 0.2

phases:

  build:
    commands:
    - echo "Build started on `date`"
    - echo "Running sbt package"
    - bash -c "source /opt/sdkman/bin/sdkman-init.sh && sbt package"

  post_build:
    commands:
    - echo "Build completed on `date`"

cache:
  paths:
  - '/root/.ivy2/cache/**/*'