version: 0.2

phases:

  build:
    commands:
    - echo "Build started on `date`"
    - echo "Running sbt package"
    - bash -c "source /opt/sdkman/bin/sdkman-init.sh && sbt package"

  post_build:
    commands:
    - echo "Build completed on `date`"

artifacts:
  files:
    - infrastructure/target/scala-2.12/infrastructure_2.12-0.1.0-SNAPSHOT.jar
    - flink-consumer/target/scala-2.12/flink-consumer_2.12-0.1.0-SNAPSHOT.jar
    - traffic-simulator/target/scala-2.12/traffic-simulator_2.12-0.1.0-SNAPSHOT.jar

cache:
  paths:
  - '/root/.ivy2/cache/**/*'